[project]
name = "ollama-example"
version = "0.1.0"
description = "A minimal example package running ollama on baskerville."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama",
]
